"""Project Intelligence read-only inspection primitives."""

from .inspector import ProjectInspectionError, inspect_workspace
from .git_tree import (
    GitTreeMaterialization,
    GitTreeMaterializationError,
    materialize_git_merge_base_subtree,
    materialize_git_subtree,
)
from .project_acquisition import (
    PLAN_FORMAT as PROJECT_ACQUISITION_PLAN_FORMAT,
    PROFILE_FORMAT as PROJECT_ACQUISITION_PROFILE_FORMAT,
    RECEIPT_FORMAT as PROJECT_ACQUISITION_RECEIPT_FORMAT,
    RESULT_FORMAT as PROJECT_ACQUISITION_RESULT_FORMAT,
    ProjectAcquisitionError,
    apply_acquisition_plan,
    build_acquisition_plan,
    load_acquisition_profile,
    resolve_remote_commit,
    resolve_acquisition_channel,
)
from ._pr_preparation_core import PullRequestPreparationError
from .pr_preparation import (
    PLAN_FORMAT as PR_PREPARATION_PLAN_FORMAT_V2,
    PROVIDER_PROFILE_FORMAT as PR_PROVIDER_PROFILE_FORMAT,
    RECEIPT_FORMAT as PR_PREPARATION_RECEIPT_FORMAT_V2,
    RESULT_FORMAT as PR_PREPARATION_RESULT_FORMAT_V2,
    apply_pr_preparation_plan_v2,
    build_pr_preparation_plan_v2,
    load_pr_preparation_receipt_v2,
    load_pull_request_provider_profile,
    observe_github_pull_request,
    verify_pr_preparation_receipt_v2,
)

from .mixin_topology import (
    ArtifactInput,
    ArtifactScanError,
    RECEIPT_FORMAT,
    build_topology_receipt,
    canonical_json_bytes,
    normalize_cleanmix_owner_id,
    render_receipt,
    scan_artifact_bytes,
    scan_artifact_paths,
)
from .mixin_receipt import validate_topology_receipt
from .mixin_dependency_closure import (
    ClassResolutionRequest,
    ClosureArtifactInput,
    DEPENDENCY_CLOSURE_FORMAT,
    DependencyEdgeInput,
    build_dependency_closure_receipt,
    find_class_resolution,
    render_dependency_closure_receipt,
    resolve_class_in_dependency_closure,
    validate_dependency_closure_receipt,
)
from .mixin_ap_compatibility import (
    AP_COMPATIBILITY_FORMAT,
    AP_COMPATIBILITY_POLICY_FORMAT,
    build_ap_compatibility_conformance_receipt,
    render_ap_compatibility_conformance_receipt,
    validate_ap_compatibility_conformance_receipt,
    validate_bound_ap_compatibility_conformance_receipt,
)
from .mixin_build_provenance import (
    ClassifiedBuildFileInput,
    ExactBuildFileInput,
    MAX_BUILD_INPUT_BYTES,
    MIXIN_BUILD_FORMAT,
    MIXIN_BUILD_INPUT_FORMAT,
    MIXIN_BUILD_POLICY_FORMAT,
    MixinCompilerAPInvocationInput,
    build_mixin_compiler_ap_build_receipt,
    render_mixin_compiler_ap_build_receipt,
    validate_bound_mixin_compiler_ap_build_receipt,
    validate_mixin_compiler_ap_build_receipt,
)
from .workspace_doctor import (
    REPORT_FORMAT as WORKSPACE_DOCTOR_FORMAT,
    WorkspaceDoctorError,
    add_finding as add_workspace_doctor_finding,
    add_next_command as add_workspace_doctor_next_command,
    discover_workspace_root,
    finalize_report as finalize_workspace_doctor_report,
    new_report as build_workspace_doctor_report,
    render_workspace_doctor_report,
    validate_workspace_doctor_report,
)
from .runtime_surface import (
    FORMAT_VERSION as RUNTIME_SURFACE_FORMAT,
    RuntimeSurfaceError,
    scan_runtime_surface,
    validate_runtime_surface,
)
from .jvm_class_surface import (
    ARCHIVE_FORMAT as JVM_ARCHIVE_SURFACE_FORMAT,
    CLASS_FORMAT as JVM_CLASS_SURFACE_FORMAT,
    inspect_class_bytes,
    scan_jvm_archive_bytes,
)


__all__ = [
    "ArtifactInput",
    "ArtifactScanError",
    "AP_COMPATIBILITY_FORMAT",
    "AP_COMPATIBILITY_POLICY_FORMAT",
    "ClassifiedBuildFileInput",
    "ClassResolutionRequest",
    "ClosureArtifactInput",
    "DEPENDENCY_CLOSURE_FORMAT",
    "DependencyEdgeInput",
    "ExactBuildFileInput",
    "MAX_BUILD_INPUT_BYTES",
    "MIXIN_BUILD_FORMAT",
    "MIXIN_BUILD_INPUT_FORMAT",
    "MIXIN_BUILD_POLICY_FORMAT",
    "JVM_ARCHIVE_SURFACE_FORMAT",
    "JVM_CLASS_SURFACE_FORMAT",
    "GitTreeMaterialization",
    "GitTreeMaterializationError",
    "MixinCompilerAPInvocationInput",
    "ProjectInspectionError",
    "ProjectAcquisitionError",
    "PullRequestPreparationError",
    "PROJECT_ACQUISITION_PLAN_FORMAT",
    "PROJECT_ACQUISITION_PROFILE_FORMAT",
    "PROJECT_ACQUISITION_RECEIPT_FORMAT",
    "PROJECT_ACQUISITION_RESULT_FORMAT",
    "PR_PREPARATION_PLAN_FORMAT_V2",
    "PR_PREPARATION_RECEIPT_FORMAT_V2",
    "PR_PREPARATION_RESULT_FORMAT_V2",
    "PR_PROVIDER_PROFILE_FORMAT",
    "RECEIPT_FORMAT",
    "RUNTIME_SURFACE_FORMAT",
    "RuntimeSurfaceError",
    "WORKSPACE_DOCTOR_FORMAT",
    "WorkspaceDoctorError",
    "add_workspace_doctor_finding",
    "add_workspace_doctor_next_command",
    "build_workspace_doctor_report",
    "build_topology_receipt",
    "build_acquisition_plan",
    "build_pr_preparation_plan_v2",
    "build_dependency_closure_receipt",
    "build_ap_compatibility_conformance_receipt",
    "build_mixin_compiler_ap_build_receipt",
    "canonical_json_bytes",
    "discover_workspace_root",
    "finalize_workspace_doctor_report",
    "normalize_cleanmix_owner_id",
    "find_class_resolution",
    "inspect_class_bytes",
    "inspect_workspace",
    "load_acquisition_profile",
    "load_pr_preparation_receipt_v2",
    "load_pull_request_provider_profile",
    "observe_github_pull_request",
    "verify_pr_preparation_receipt_v2",
    "materialize_git_merge_base_subtree",
    "materialize_git_subtree",
    "render_dependency_closure_receipt",
    "render_ap_compatibility_conformance_receipt",
    "render_mixin_compiler_ap_build_receipt",
    "render_workspace_doctor_report",
    "resolve_class_in_dependency_closure",
    "resolve_remote_commit",
    "resolve_acquisition_channel",
    "render_receipt",
    "scan_artifact_bytes",
    "scan_artifact_paths",
    "scan_jvm_archive_bytes",
    "scan_runtime_surface",
    "validate_topology_receipt",
    "validate_runtime_surface",
    "validate_dependency_closure_receipt",
    "validate_ap_compatibility_conformance_receipt",
    "validate_bound_ap_compatibility_conformance_receipt",
    "validate_bound_mixin_compiler_ap_build_receipt",
    "validate_mixin_compiler_ap_build_receipt",
    "validate_workspace_doctor_report",
    "apply_acquisition_plan",
    "apply_pr_preparation_plan_v2",
]
