"""Surface-neutral Workbench integration foundation and console metadata.

The package-level API is intentionally lazy.  Importing one focused Workbench
port must not initialize every runtime, server, graph, and IDE dependency.
Names in ``__all__`` retain their existing public meaning and are loaded from
their owning module on first access.
"""

from importlib import import_module


_EXPORT_GROUPS = {
    ".catalog": ("Catalog", "CatalogError", "CommandSpec", "FieldSpec", "build_catalog"),
    ".active_instance": ("ActiveInstanceError", "initialize_active_instance", "load_active_instance"),
    ".blueprint_stage": ("BlueprintStageError", "plan_material_backed_fluid", "stage_material_backed_fluid"),
    ".bootstrap": ("discover_suite_root", "inspect_project"),
    ".workspace_home": ("WorkspaceHomeError", "build_workspace_home", "validate_workspace_home"),
    ".susy_mod_dev": ("SusyModDevError", "execute_susy_mod_build", "plan_susy_mod_dev", "render_susy_mod_plan", "render_susy_mod_result", "validate_susy_mod_plan"),
    ".susy_mod_check": ("SusyModCheckError", "check_susy_mod_server", "render_susy_mod_check"),
    ".susy_mod_launch": ("SusyModLaunchError", "launch_susy_mod_client", "render_susy_mod_launch"),
    ".susy_mod_run": ("DEV_RUN_RECEIPT_FORMAT", "DEV_RUN_RESULT_FORMAT", "DEV_RUN_SIDES", "SusyModRunError", "reopen_susy_mod_run", "render_susy_mod_run", "run_susy_mod"),
    ".susy_mod_server": ("SusyModServerError", "launch_susy_mod_server", "render_susy_mod_server"),
    ".susy_server_materialize": ("MATERIALIZATION_RECEIPT_FORMAT_V2", "MATERIALIZATION_RESULT_FORMAT_V2", "SusyServerMaterializationError", "materialize_susy_server", "render_susy_server_materialization", "susy_server_materialization_version", "verify_susy_server_materialization_receipt_identity"),
    ".component_graph": ("Component", "ComponentGraph", "ComponentGraphError", "load_component_graph"),
    "workbench_core.configuration": ("CONFIGURATION_PATH", "SCHEMA", "ResolvedBindings", "WorkbenchConfiguration", "WorkbenchConfigurationError", "load_workbench_configuration"),
    ".material_fluid_flow": ("MaterialFluidFlowError", "execute_material_fluid_trial", "plan_material_fluid_trial"),
    ".feature_studio": ("FeatureStudioError", "execute_feature_request", "explain_feature", "export_feature", "feature_studio_capabilities", "inspect_feature", "inspect_retained_feature", "plan_feature", "preview_feature", "verify_feature", "validate_feature_request", "validate_feature_result"),
    ".feature_studio_snapshot": ("open_feature_snapshot", "project_feature_snapshot", "refresh_feature_snapshot", "refresh_feature_snapshot_file", "validate_feature_snapshot"),
    ".protocol": ("ProtocolSession",),
    ".runtime_bootstrap": ("RuntimeBootstrapError", "bootstrap_project_runtime", "materialize_client_bootstrap"),
    ".runtime_compatibility": ("RuntimeCompatibilityError",),
    ".runtime_anvil_observe": ("RuntimeAnvilObserveError", "observe_runtime_anvil_worlds"),
    ".runtime_diagnose": ("RuntimeDiagnosisError", "diagnose_project_runtime", "load_verified_runtime_evidence"),
    ".runtime_recipe_reload_diagnostic": ("RuntimeRecipeDiagnosticError", "compare_project_recipe_reload", "diagnose_project_recipe_reload"),
    ".runtime_recipe_invalidation_diagnostic": ("RuntimeRecipeInvalidationError", "compare_project_recipe_invalidations", "diagnose_project_recipe_invalidations"),
    ".runtime_worldgen_audit": ("RuntimeWorldgenAuditError", "audit_project_worldgen"),
    ".runtime_worldgen_fingerprint": ("RuntimeWorldgenFingerprintError", "attribute_runtime_worldgen_blocks", "compare_runtime_worldgen", "fingerprint_runtime_worldgen"),
    "workbench_core.runtime_java": ("JavaRuntimeError", "discover_java_runtime", "ensure_java_runtime", "host_platform", "load_java_runtime_policy", "materialize_temurin_runtime", "probe_java", "resolve_temurin_asset"),
    ".runtime_launch": ("RuntimeLaunchError", "launch_materialized_client", "launch_project_runtime"),
    ".runtime_observe": ("RuntimeObserveError", "observe_project_runtime"),
    ".runtime_materialize": ("PackwizMaterializationError", "materialize_packwiz_workspace_v2", "materialize_project_runtime", "packwiz_materialization_version", "verify_packwiz_materialization_receipt_identity"),
    ".runtime_plan": ("RuntimePlanError", "build_runtime_plan", "plan_project_runtime"),
    ".registration_wizard": ("RegistrationWizardError", "apply_active_registration", "plan_active_registration", "registration_capabilities"),
    ".diagnose_reproduce": ("DiagnoseReproduceV2Error", "create_reproduction_capsule", "diagnose_live_console", "inspect_reproduction_capsule", "replay_reproduction_capsule", "validate_diagnosis", "validate_reproduction_capsule_manifest"),
    ".cleanroom_dev_loop": ("CleanroomDevLoopError", "execute_cleanroom_dev_loop", "find_cleanroom_dev_loop_stage", "load_cleanroom_dev_loop_receipt", "plan_cleanroom_dev_loop", "recover_cleanroom_dev_loop", "validate_cleanroom_dev_loop_plan", "validate_cleanroom_dev_loop_receipt"),
    ".feature_change_workspace": ("FeatureChangeWorkspaceError", "apply_feature_change", "open_feature_change", "recover_feature_change", "rollback_feature_change", "run_feature_change_matrix", "start_material_fluid_recipe_change", "verify_feature_change"),
    ".cleanroom_new_project_cli": ("CleanroomNewProjectCliV2Error", "load_cleanroom_mod_construction_owner", "validate_cleanroom_mod_construction_owner"),
}
_LAZY_EXPORTS = {
    name: module_name
    for module_name, names in _EXPORT_GROUPS.items()
    for name in names
}


def __getattr__(name: str):
    module_name = _LAZY_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
__all__ = [
    "Catalog",
    "CatalogError",
    "CommandSpec",
    "FieldSpec",
    "ActiveInstanceError",
    "BlueprintStageError",
    "Component",
    "ComponentGraph",
    "ComponentGraphError",
    "CONFIGURATION_PATH",
    "SCHEMA",
    "ResolvedBindings",
    "WorkbenchConfiguration",
    "WorkbenchConfigurationError",
    "JavaRuntimeError",
    "MaterialFluidFlowError",
    "FeatureStudioError",
    "DiagnoseReproduceV2Error",
    "CleanroomDevLoopError",
    "FeatureChangeWorkspaceError",
    "CleanroomNewProjectCliV2Error",
    "PackwizMaterializationError",
    "ProtocolSession",
    "RegistrationWizardError",
    "RuntimeBootstrapError",
    "RuntimeCompatibilityError",
    "RuntimeAnvilObserveError",
    "RuntimeDiagnosisError",
    "RuntimeRecipeDiagnosticError",
    "RuntimeWorldgenAuditError",
    "RuntimeWorldgenFingerprintError",
    "RuntimeLaunchError",
    "WorkspaceHomeError",
    "RuntimeObserveError",
    "RuntimePlanError",
    "SusyModDevError",
    "SusyModCheckError",
    "SusyModLaunchError",
    "SusyModRunError",
    "SusyModServerError",
    "SusyServerMaterializationError",
    "MATERIALIZATION_RECEIPT_FORMAT_V2",
    "MATERIALIZATION_RESULT_FORMAT_V2",
    "DEV_RUN_RECEIPT_FORMAT",
    "DEV_RUN_RESULT_FORMAT",
    "DEV_RUN_SIDES",
    "apply_active_registration",
    "bootstrap_project_runtime",
    "build_catalog",
    "build_workspace_home",
    "build_runtime_plan",
    "check_susy_mod_server",
    "discover_suite_root",
    "discover_java_runtime",
    "diagnose_project_runtime",
    "diagnose_live_console",
    "compare_project_recipe_reload",
    "diagnose_project_recipe_reload",
    "RuntimeRecipeInvalidationError",
    "compare_project_recipe_invalidations",
    "diagnose_project_recipe_invalidations",
    "audit_project_worldgen",
    "attribute_runtime_worldgen_blocks",
    "compare_runtime_worldgen",
    "ensure_java_runtime",
    "fingerprint_runtime_worldgen",
    "host_platform",
    "inspect_project",
    "inspect_reproduction_capsule",
    "initialize_active_instance",
    "load_component_graph",
    "load_workbench_configuration",
    "load_java_runtime_policy",
    "load_cleanroom_dev_loop_receipt",
    "load_cleanroom_mod_construction_owner",
    "load_verified_runtime_evidence",
    "load_active_instance",
    "launch_materialized_client",
    "launch_project_runtime",
    "launch_susy_mod_client",
    "launch_susy_mod_server",
    "reopen_susy_mod_run",
    "run_susy_mod",
    "observe_project_runtime",
    "observe_runtime_anvil_worlds",
    "materialize_client_bootstrap",
    "materialize_packwiz_workspace_v2",
    "materialize_project_runtime",
    "packwiz_materialization_version",
    "verify_packwiz_materialization_receipt_identity",
    "materialize_temurin_runtime",
    "materialize_susy_server",
    "susy_server_materialization_version",
    "verify_susy_server_materialization_receipt_identity",
    "execute_material_fluid_trial",
    "execute_susy_mod_build",
    "execute_feature_request",
    "execute_cleanroom_dev_loop",
    "find_cleanroom_dev_loop_stage",
    "create_reproduction_capsule",
    "explain_feature",
    "export_feature",
    "feature_studio_capabilities",
    "inspect_feature",
    "inspect_retained_feature",
    "plan_feature",
    "plan_cleanroom_dev_loop",
    "preview_feature",
    "verify_feature",
    "validate_feature_request",
    "validate_feature_result",
    "open_feature_snapshot",
    "project_feature_snapshot",
    "refresh_feature_snapshot",
    "refresh_feature_snapshot_file",
    "validate_feature_snapshot",
    "plan_material_backed_fluid",
    "plan_material_fluid_trial",
    "plan_project_runtime",
    "plan_susy_mod_dev",
    "plan_active_registration",
    "probe_java",
    "resolve_temurin_asset",
    "registration_capabilities",
    "replay_reproduction_capsule",
    "validate_diagnosis",
    "validate_reproduction_capsule_manifest",
    "recover_cleanroom_dev_loop",
    "validate_cleanroom_dev_loop_plan",
    "validate_cleanroom_dev_loop_receipt",
    "validate_cleanroom_mod_construction_owner",
    "start_material_fluid_recipe_change",
    "open_feature_change",
    "run_feature_change_matrix",
    "apply_feature_change",
    "verify_feature_change",
    "rollback_feature_change",
    "recover_feature_change",
    "render_susy_mod_plan",
    "render_susy_mod_check",
    "render_susy_mod_result",
    "render_susy_mod_launch",
    "render_susy_mod_run",
    "render_susy_mod_server",
    "render_susy_server_materialization",
    "stage_material_backed_fluid",
    "validate_workspace_home",
    "validate_susy_mod_plan",
]
