"""Historical fixed-path fixture projections can be adopted without replacement."""

from hashlib import sha256
from concurrent.futures import ThreadPoolExecutor
import os
from pathlib import Path
import shutil
import tempfile
import unittest
from unittest.mock import patch

from workbench_api.durable_resources import DurableResourceError
from workbench_api.reusable_projections import ReusableProjectionError
from workbench_core import check_storage
from workbench_core.host_filesystem import HostFilesystemError
from workbench_core.reusable_projections import CoreReusableProjections
from workbench_core.storage.registered import ResourceCatalog


class ReusableProjectionTests(unittest.TestCase):
    def setUp(self) -> None:
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.home = Path(temporary.name).resolve()
        self.workspace = self.home / "workspace"
        self.workspace.mkdir()
        self.content = b"plugin=fixture\n"
        self.digest = "sha256:" + sha256(self.content).hexdigest()
        self.root = self.home / "state/source-projections/cleanroom" / self.digest[7:]
        self.project_relative = Path("profiles/platforms/cleanroom/fixtures/example")
        self.project = self.root / self.project_relative
        self.project.mkdir(parents=True, mode=0o700)
        for parent in (self.root, *self.project.parents):
            if parent.is_relative_to(self.home / "state"):
                parent.chmod(0o700)
        self.source = self.project / "build.gradle"
        self.source.write_bytes(self.content)
        self.source.chmod(0o600)
        self.rows = ({
            "path": "build.gradle", "sha256": self.digest, "size": len(self.content),
        },)
        self.host = CoreReusableProjections(
            workspace=self.workspace, configuration_home=self.home / "config", owner_id="cleanroom",
        )

    def _adopt(self, *, generated_roots: tuple[Path, ...] = ()):
        return self.host.adopt(
            "cleanroom", self.root, source_digest=self.digest,
            project_relative=self.project_relative, source_files=self.rows,
            generated_parts=("build", ".gradle"), generated_suffixes=(".jar", ".class"),
            validate=lambda project: self.assertEqual(project, self.project),
            generated_roots=generated_roots,
        )

    def _create(self):
        source_root = self.home / "canonical-fixture"
        source_root.mkdir(exist_ok=True)
        (source_root / "build.gradle").write_bytes(self.content)
        if self.root.exists():
            shutil.rmtree(self.root)
        return self._ensure(source_root)

    def _ensure(self, source_root: Path):
        return self.host.ensure(
            "cleanroom", self.root, source_root=source_root,
            source_digest=self.digest, project_relative=self.project_relative,
            source_files=self.rows, generated_parts=("build", ".gradle"),
            generated_suffixes=(".jar", ".class"),
            validate=lambda project: self.assertEqual(self.content, (project / "build.gradle").read_bytes()),
        )

    def test_core_publishes_new_projection_and_registers_narrow_root(self) -> None:
        reference = self._create()
        self.assertEqual(self.root, reference.path)
        self.assertEqual(self.content, self.source.read_bytes())
        stores = self.host.catalog.inventory(workspace=self.workspace)["record_stores"]
        self.assertIn(str(self.root.parent), {row["path"] for row in stores})
        self.assertFalse(self.root.with_name(f".{self.root.name}.stage").exists())
        generated = self.project / "build/classes/example.class"
        generated.parent.mkdir(parents=True)
        generated.write_bytes(b"retained generated bytes")
        identity = self.root.stat().st_ino
        reused = self.host.ensure(
            "cleanroom", self.root, source_root=self.home / "canonical-fixture",
            source_digest=self.digest, project_relative=self.project_relative,
            source_files=self.rows, generated_parts=("build", ".gradle"),
            generated_suffixes=(".jar", ".class"),
            validate=lambda project: self.assertEqual(self.content, (project / "build.gradle").read_bytes()),
        )
        self.assertEqual(reference, reused)
        self.assertEqual(identity, self.root.stat().st_ino)
        self.assertEqual(b"retained generated bytes", generated.read_bytes())

    def test_resource_catalog_closes_foreign_record_before_filter_without_owner_scan(self) -> None:
        selected = self._adopt()
        foreign = self.home / "foreign-workspace"
        foreign.mkdir()
        foreign_root = self.home / "foreign-state/source-projections/cleanroom" / self.digest[7:]
        foreign_project = foreign_root / self.project_relative
        foreign_project.mkdir(parents=True, mode=0o700)
        for parent in (foreign_root, *foreign_project.parents):
            if parent.is_relative_to(self.home / "foreign-state"):
                parent.chmod(0o700)
        (foreign_project / "build.gradle").write_bytes(self.content)
        other_host = CoreReusableProjections(
            workspace=foreign, configuration_home=self.home / "config", owner_id="cleanroom",
        )
        other = other_host.adopt(
            "cleanroom", foreign_root, source_digest=self.digest,
            project_relative=self.project_relative, source_files=self.rows,
            generated_parts=("build", ".gradle"), generated_suffixes=(".jar", ".class"),
            validate=lambda _: None,
        )
        catalog = ResourceCatalog(self.home / "config")
        with patch("workbench_core.reusable_projections._scan", side_effect=AssertionError("owner scan")):
            inventory = catalog.inventory(workspace=self.workspace)
        self.assertEqual("ready-unproven", inventory["root_state"])
        self.assertEqual([selected.projection_id], [
            row["projection_id"] for row in inventory["reusable_projections"]
        ])
        self.assertEqual("catalog-only", inventory["reusable_projections"][0]["status"])
        self.assertEqual("absent", inventory["reusable_projections"][0]["parent_store_registration"])
        self.assertIsNone(inventory["reusable_projections"][0]["parent_store_id"])
        self.assertEqual([other.projection_id], [
            row["projection_id"] for row in catalog.inventory(workspace=foreign)["reusable_projections"]
        ])

        original = other_host._record(other.projection_id)
        for generated_parts in (["build", "build"], [".gradle", "build", "build.gradle"]):
            with self.subTest(generated_parts=generated_parts):
                forged = {**original, "generated_parts": generated_parts}
                binding = {key: forged[key] for key in (
                    "family", "path", "source_digest", "project_relative", "source_files",
                    "generated_parts", "generated_suffixes", "owner_id", "workspace",
                )}
                nonce = sha256(check_storage.canonical(binding)).hexdigest()
                forged["projection_id"] = f"workbench-reusable-projection-v1:{nonce}"
                forged.pop("id")
                forged = check_storage.seal("workbench-reusable-projection-v1", forged)
                path = catalog.root / "reusable-projections/records" / f"{nonce}.json"
                path.write_bytes(check_storage.canonical(forged))
                path.chmod(0o600)
                try:
                    with self.assertRaises(DurableResourceError) as caught:
                        catalog.inventory(workspace=self.workspace)
                    self.assertEqual("resource.changed", caught.exception.code)
                finally:
                    path.unlink()
        self.assertEqual([selected.projection_id], [
            row["projection_id"] for row in catalog.inventory(workspace=self.workspace)["reusable_projections"]
        ])

    def test_parent_store_declaration_is_observed_without_repairing_missing_history(self) -> None:
        reference = self._create()
        catalog = ResourceCatalog(self.home / "config")
        first = catalog.inventory(workspace=self.workspace)
        row = first["reusable_projections"][0]
        self.assertEqual(reference.projection_id, row["projection_id"])
        self.assertEqual("present", row["parent_store_registration"])
        self.assertEqual("ready-unproven", first["root_state"])
        store_id = row["parent_store_id"]
        self.assertIsInstance(store_id, str)

        registration = catalog.root / "stores" / f"{store_id.rsplit(':', 1)[1]}.json"
        registration.unlink()
        with patch("workbench_core.reusable_projections._scan", side_effect=AssertionError("owner scan")):
            after = catalog.inventory(workspace=self.workspace)
        self.assertEqual("ready-unproven", after["root_state"])
        self.assertEqual(reference.projection_id, after["reusable_projections"][0]["projection_id"])
        self.assertEqual("absent", after["reusable_projections"][0]["parent_store_registration"])
        self.assertIsNone(after["reusable_projections"][0]["parent_store_id"])

    def test_resource_catalog_preserves_pre_record_locks_and_refuses_unknown_children(self) -> None:
        selected = self._adopt()
        catalog = ResourceCatalog(self.home / "config")
        namespace = catalog.root / "reusable-projections"
        foreign = self.home / "foreign-workspace"
        foreign.mkdir()
        for name in ("leases", "publication-leases"):
            lock = namespace / name / ("a" * 64 + ".lock")
            lock.touch(mode=0o600)
            try:
                self.assertEqual([], catalog.inventory(workspace=foreign)["reusable_projections"])
            finally:
                lock.unlink()
        unknown = namespace / "records" / "unknown.pending"
        unknown.write_bytes(b"{}")
        unknown.chmod(0o600)
        try:
            with self.assertRaises(DurableResourceError) as caught:
                catalog.inventory(workspace=foreign)
            self.assertEqual("resource.changed", caught.exception.code)
        finally:
            unknown.unlink()
        self.assertEqual([selected.projection_id], [
            row["projection_id"] for row in catalog.inventory(workspace=self.workspace)["reusable_projections"]
        ])

    def test_resource_catalog_preserves_exact_interrupted_record_stages(self) -> None:
        selected = self._adopt()
        catalog = ResourceCatalog(self.home / "config")
        records = catalog.root / "reusable-projections/records"
        foreign = self.home / "foreign-workspace"
        foreign.mkdir()

        descriptor, pending_name = tempfile.mkstemp(prefix=f".{'b' * 64}.json.", dir=records)
        os.close(descriptor)
        pending = Path(pending_name)
        pending.write_bytes(b"partial record before publication")
        pending.chmod(0o600)
        try:
            self.assertEqual([], catalog.inventory(workspace=foreign)["reusable_projections"])
        finally:
            pending.unlink()

        nonce = selected.projection_id.removeprefix("workbench-reusable-projection-v1:")
        published = records / f"{nonce}.json"
        linked_stage = records / f".{nonce}.json.abcdefgh"
        os.link(published, linked_stage)
        try:
            self.assertEqual([selected.projection_id], [
                row["projection_id"] for row in catalog.inventory(workspace=self.workspace)["reusable_projections"]
            ])
            with self.host.open(selected.projection_id, validate=lambda _: None) as reopened:
                self.assertEqual(selected, reopened)
        finally:
            linked_stage.unlink()

        outside = self.home / "outside-record"
        outside.write_bytes(b"unrelated hard link")
        outside.chmod(0o600)
        os.link(outside, pending)
        try:
            with self.assertRaises(DurableResourceError) as caught:
                catalog.inventory(workspace=foreign)
            self.assertEqual("resource.changed", caught.exception.code)
        finally:
            pending.unlink()

    def test_complete_interrupted_stage_resumes_and_incomplete_one_blocks(self) -> None:
        with patch(
            "workbench_core.reusable_projections._rename_noreplace",
            side_effect=OSError("injected publication interruption"),
        ):
            with self.assertRaisesRegex(ReusableProjectionError, "cannot be published"):
                self._create()
        stage = self.root.with_name(f".{self.root.name}.stage")
        self.assertTrue(stage.is_dir())
        self.assertFalse(self.root.exists())
        self.assertIn(
            str(self.root.parent),
            {row["path"] for row in self.host.catalog.inventory(workspace=self.workspace)["record_stores"]},
        )
        self.assertEqual([], self.host.catalog.inventory(workspace=self.workspace)["reusable_projections"])
        recovered = self._create()
        self.assertEqual(self.root, recovered.path)
        self.assertFalse(stage.exists())

        shutil.rmtree(self.root)
        with patch(
            "workbench_core.reusable_projections._rename_noreplace",
            side_effect=OSError("injected publication interruption"),
        ):
            with self.assertRaises(ReusableProjectionError):
                self._create()
        generated = stage / self.project_relative / "build/output.class"
        generated.parent.mkdir(parents=True)
        generated.write_bytes(b"unreviewed generated output")
        with self.assertRaisesRegex(ReusableProjectionError, "requires review"):
            self._create()
        self.assertEqual(b"unreviewed generated output", generated.read_bytes())
        shutil.rmtree(stage)
        stage.mkdir(mode=0o700)
        with self.assertRaisesRegex(ReusableProjectionError, "requires review"):
            self._create()
        self.assertTrue(stage.is_dir())
        self.assertFalse(self.root.exists())

    def test_registration_failure_prevents_publication(self) -> None:
        source_root = self.home / "canonical-fixture"
        source_root.mkdir()
        (source_root / "build.gradle").write_bytes(self.content)
        shutil.rmtree(self.root)
        with patch.object(self.host.catalog, "register_record_store", side_effect=OSError("injected catalog failure")):
            with self.assertRaisesRegex(ReusableProjectionError, "Core custody"):
                self.host.ensure(
                    "cleanroom", self.root, source_root=source_root,
                    source_digest=self.digest, project_relative=self.project_relative,
                    source_files=self.rows, generated_parts=("build",),
                    generated_suffixes=(".jar",), validate=lambda _: None,
                )
        self.assertFalse(self.root.exists())
        self.assertFalse(self.root.with_name(f".{self.root.name}.stage").exists())

    def test_private_mode_failure_prevents_stage_on_wsl_style_mount(self) -> None:
        source_root = self.home / "canonical-fixture"
        source_root.mkdir()
        (source_root / "build.gradle").write_bytes(self.content)
        shutil.rmtree(self.root)
        with patch(
            "workbench_core.reusable_projections.secure_private_path",
            side_effect=HostFilesystemError("private mode unavailable"),
        ):
            with self.assertRaisesRegex(ReusableProjectionError, "private Core custody"):
                self._ensure(source_root)
        self.assertFalse(self.root.exists())
        self.assertFalse(self.root.with_name(f".{self.root.name}.stage").exists())

    def test_concurrent_same_digest_publication_reuses_one_tree(self) -> None:
        source_root = self.home / "canonical-fixture"
        source_root.mkdir()
        (source_root / "build.gradle").write_bytes(self.content)
        shutil.rmtree(self.root)
        self.host._ensure()
        with ThreadPoolExecutor(max_workers=2) as executor:
            references = list(executor.map(self._ensure, (source_root, source_root)))
        self.assertEqual(references[0], references[1])
        self.assertEqual(self.content, self.source.read_bytes())
        self.assertFalse(self.root.with_name(f".{self.root.name}.stage").exists())

    def test_exact_generated_sibling_is_reusable_but_unrelated_sibling_is_rejected(self) -> None:
        generated_root = Path(".workbench/build/cleanroom/0.6.8-alpha/generic-mod-daily-loop")
        generated = self.root / generated_root / "libs/fixture.jar"
        generated.parent.mkdir(parents=True)
        generated.write_bytes(b"prior Gradle artifact")
        reference = self._adopt(generated_roots=(generated_root,))
        with self.host.open(reference.projection_id, validate=lambda _: None):
            generated.write_bytes(b"new Gradle artifact")
        (self.root / "unrelated").mkdir()
        with self.assertRaisesRegex(ReusableProjectionError, "unexpected member"):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass

    def test_historical_tree_is_adopted_in_place_and_generated_cache_reused(self) -> None:
        old_root_inode = self.root.stat().st_ino
        generated = self.project / "build/classes/output.class"
        generated.parent.mkdir(parents=True)
        generated.write_bytes(b"old build")
        loose_generated = self.project / "generated.jar"
        loose_generated.write_bytes(b"old artifact")
        reference = self._adopt()
        self.assertEqual(old_root_inode, self.root.stat().st_ino)
        self.assertEqual(b"old build", generated.read_bytes())
        self.assertEqual(b"old artifact", loose_generated.read_bytes())
        with self.host.open(reference.projection_id, validate=lambda _: None) as opened:
            self.assertEqual(reference, opened)
            generated.write_bytes(b"new build")
        with self.host.open(reference.projection_id, validate=lambda _: None) as opened:
            self.assertEqual(reference, opened)
        self.assertEqual(reference, self._adopt())

    def test_source_tamper_and_undeclared_file_rejected(self) -> None:
        reference = self._adopt()
        self.source.write_bytes(b"changed source")
        with self.assertRaises(ReusableProjectionError):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass
        self.source.write_bytes(self.content)
        (self.project / "surprise.txt").write_bytes(b"not generated")
        with self.assertRaisesRegex(ReusableProjectionError, "undeclared source"):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass

    def test_owner_validation_cannot_mutate_admitted_source(self) -> None:
        reference = self._adopt()

        def mutate(_: Path) -> None:
            self.source.write_bytes(self.content + b"changed")

        with self.assertRaisesRegex(ReusableProjectionError, "source changed"):
            with self.host.open(reference.projection_id, validate=mutate):
                pass

    def test_owner_validation_cannot_add_undeclared_member(self) -> None:
        reference = self._adopt()

        def mutate(_: Path) -> None:
            (self.project / "unexpected.txt").write_bytes(b"new")

        with self.assertRaisesRegex(ReusableProjectionError, "undeclared source"):
            with self.host.open(reference.projection_id, validate=mutate):
                pass

    def test_declared_source_aggregate_is_bounded(self) -> None:
        rows = (
            {"path": "first", "sha256": self.digest, "size": 16 * 1024 * 1024},
            {"path": "second", "sha256": self.digest, "size": 1},
        )
        with self.assertRaisesRegex(ReusableProjectionError, "exceed 16 MiB"):
            self.host.adopt(
                "cleanroom", self.root, source_digest=self.digest,
                project_relative=self.project_relative, source_files=rows,
                generated_parts=("build",), generated_suffixes=(), validate=lambda _: None,
            )

    def test_replaced_root_and_generated_symlink_rejected(self) -> None:
        reference = self._adopt()
        saved = self.root.with_name(self.root.name + "-saved")
        self.root.rename(saved)
        self.root.mkdir(mode=0o700)
        new_project = self.root / self.project_relative
        new_project.mkdir(parents=True, mode=0o700)
        (new_project / "build.gradle").write_bytes(self.content)
        with self.assertRaisesRegex(ReusableProjectionError, "replaced"):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass
        # Restore the exact original directory, then inspect an unsafe cache.
        import shutil
        shutil.rmtree(self.root)
        saved.rename(self.root)
        (self.project / "build").symlink_to(self.home, target_is_directory=True)
        with self.assertRaisesRegex(ReusableProjectionError, "redirect"):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass

    def test_replaced_parent_is_rejected(self) -> None:
        reference = self._adopt()
        parent = self.root.parent
        saved = parent.with_name(parent.name + "-saved")
        parent.rename(saved)
        parent.mkdir(mode=0o700)
        import shutil
        shutil.copytree(saved / self.root.name, self.root)
        with self.assertRaisesRegex(ReusableProjectionError, "replaced"):
            with self.host.open(reference.projection_id, validate=lambda _: None):
                pass

    @unittest.skipUnless(os.name == "posix", "Unix private mode check")
    def test_nonprivate_projection_is_rejected_without_chmod_adoption(self) -> None:
        self.root.chmod(0o755)
        with self.assertRaisesRegex(ReusableProjectionError, "owner-private"):
            self._adopt()
        self.assertEqual(0o755, self.root.stat().st_mode & 0o777)


if __name__ == "__main__":
    unittest.main()
