#!/usr/bin/env python3
"""Native JAR metadata/dependency witnesses and complete-artifact comparisons."""
import argparse
from hashlib import sha256
import json
import re
from pathlib import Path

import axiom_pack_configuration_conformance as configuration
import axiom_pack_addon_discovery_conformance as addon
import axiom_pack_gtfo_configuration_conformance as gtfo
from axiom_material_program_cases import identity, source_acknowledgement, matches_source_acknowledgement
from axiom_material_program_sources import selected_revisions
from build_axiom_target import git

INJECTED = 'config/injectedDependencies.json'
BASE_AFTER = ['gregtech@[2.8.0-beta,)', 'gcy_science', 'nutrition']
EXCLUDED = {'codechicken.microblock.handler.MicroblockMod$', 'codechicken.multipart.handler.MultipartMod$',
            'mrtjp.core.handler.MrTJPCoreMod$', 'li.cil.oc.OpenComputers$', 'mrtjp.projectred.ProjectRedCore$',
            'mrtjp.projectred.ProjectRedIllumination$', 'mrtjp.projectred.ProjectRedIntegration$',
            'mrtjp.projectred.ProjectRedTransmission$'}


def injection(*deps):
    return json.dumps([{'modId': 'gregtechfoodoption', 'deps': list(deps)}]).encode()


def corpus(sussy, saved):
    base = gtfo.corpus(sussy, saved)[0]['files']
    after = {'type': 'after', 'target': 'applecore@[3.4,)'}
    before = {'type': 'before', 'target': 'susy'}
    result = []
    for name, raw, a, b, error in (
            ('no-injections', None, [], [], False),
            ('native-before', injection(before), [], ['susy'], False),
            ('native-after', injection(after), ['applecore@[3.4,)'], [], False),
            ('native-duplicates-retained', injection(after, after), ['applecore@[3.4,)']*2, [], False),
            ('native-invalid-json', b'not valid json', [], [], True),
            ('native-partial-error', injection(after, {'type': 'invalid', 'target': 'susy'}), ['applecore@[3.4,)'], [], True),
            ('native-empty-array', b'[]', [], [], False),
            ('fresh-restoration', None, [], [], False)):
        files = dict(base)
        if raw is not None: files[INJECTED] = raw
        result.append({'name': name, 'files': files, 'after': a, 'before': b, 'dependency_error': error})
    return result


def check_metadata(case, execution):
    failures = []
    d = execution.get('addonDiscovery', {}); c = d.get('nativeCandidateDiscovery', {})
    expected = {'method': 'original ModCandidate.explore -> JarDiscoverer -> ModContainerFactory -> bindMetadata',
                'artifacts': 184, 'containers': 162, 'completeAsmSubscriberTable': False, 'activationQualified': False}
    if any(c.get(k) != v for k, v in expected.items()): failures.append('native candidate scope/count differs')
    if c.get('inputScope') not in ('entrypoints-and-metadata', 'complete-artifacts'):
        failures.append('native candidate byte scope missing')
    order = c.get('candidateOrder', [])
    if len(order) != 162 or len(set(order)) != 162 or not {'gregtechfoodoption', 'applecore', 'susy', 'gcym'} <= set(order):
        failures.append('native candidate identities/order missing or duplicated')
    if any(id in order for id in ('nuclearcraft', 'actuallyadditions', 'gcys')):
        failures.append('unknown query ID injected into candidate list')
    exclusions = c.get('classEntryExclusions', [])
    if len(exclusions) != 8 or {r.get('class') for r in exclusions} != EXCLUDED:
        failures.append('native Scala companion entry filtering differs')
    if len(c.get('metadataSha256', '')) != 64: failures.append('native metadata identity absent')
    dependencies = c.get('injectedDependencies', {}); raw = case['files'].get(INJECTED)
    expected_deps = {'method': 'original Loader.readInjectedDependencies', 'filePresent': raw is not None,
                     'after': {'gregtechfoodoption': case['after']} if case.get('after') else {},
                     'before': {'gregtechfoodoption': case['before']} if case.get('before') else {}}
    if raw is not None: expected_deps['inputSha256'] = sha256(raw).hexdigest()
    if dependencies != expected_deps: failures.append('native injected dependency state/custody differs')
    g = d.get('gtfoNativeCandidate', {})
    for k, v in {'class': 'gregtechfoodoption.GregTechFoodOption', 'modId': 'gregtechfoodoption',
                 'version': '1.12.10', 'classVersion': 52, 'autogeneratedMetadata': False,
                 'minecraftRange': '[1.12.2,1.12.2]', 'requirements': ['gregtech@[2.8.0-beta,)'],
                 'after': BASE_AFTER+case.get('after', []), 'before': case.get('before', [])}.items():
        if g.get(k) != v: failures.append('native GTFO metadata differs: '+k)
    apple = d.get('queries', {}).get('applecore', {}).get('nativeCandidate', {})
    if any(apple.get(k) != v for k, v in {'class': 'squeek.applecore.AppleCore', 'version': '3.4.0',
            'autogeneratedMetadata': True, 'requirements': ['forge@[14.23,)'], 'after': ['forge@[14.23,)']}.items()):
        failures.append('native AppleCore metadata fallback/dependencies differ')
    return failures


def check_dependency_errors(case, execution):
    # Forge logs are captured by the native log observer, not Groovy's script log.
    diagnostics = [r for r in execution.get('diagnostics', []) if r.get('severity') == 'error']
    if not case.get('dependency_error'):
        return ['unexpected native metadata/material errors'] if diagnostics or execution.get('nativeErrors') else []
    expected = [r for r in diagnostics if 'Unable to parse' in r.get('message', '')
                and 'injectedDependencies.json' in r['message']]
    if not expected:
        return ['original caught dependency-reader error missing']
    if any(r.get('locations') != [] or r.get('locationStatus') != 'unlocated' for r in expected):
        return ['native configuration error given a fabricated source location']
    if not any(r.get('trace') and r.get('causality', {}).get('exceptions') for r in diagnostics):
        return ['original caught dependency-reader exception evidence missing']
    return []


def check_result(case, response, exit_code):
    body = response.get('result', {}); e = body.get('execution', {})
    failures = gtfo.check_configuration(case, e)+addon.check_discovery(case, e)+check_metadata(case, e)
    failures += configuration.check_initialization(case, e)
    if (exit_code != 4 or response.get('status') != 'incomplete' or body.get('nativeOutcome') != 'incomplete'
            or body.get('wholePackParity') is not False or not matches_source_acknowledgement(body.get('sourceProgram'), case['files'])
            or e.get('candidateAdmissionViolations') != [] or e.get('phase') != 'FROZEN'
            or e.get('nativeException') or e.get('registeredMaterials') != (3441 if case['name'] == 'pack' else 648)):
        failures.append('native material execution/custody regressed')
    failures += check_dependency_errors(case, e)
    if not body.get('transformations', {}).get('gregtechfoodoption.GTFOConfig'):
        failures.append('native GTFO config transformation absent')
    for key in ('materialEventDispatch', 'postMaterialEventDispatch'):
        if any('gregtechfoodoption.GTFOEventHandler' in row.get('handler', '') for row in e.get(key, {}).get('listeners', [])):
            failures.append('unqualified GTFO callback registered')
    return failures


def comparable(run):
    e = run['response']['result']['execution']; d = e['addonDiscovery']
    c = {k: v for k, v in d['nativeCandidateDiscovery'].items() if k not in ('inputScope', 'inputBytes')}
    # The original reader logs the fresh worker's absolute path. Compare its
    # stable message content; keep untouched messages/traces in both raw receipts.
    diagnostics = [{'severity': r['severity'], 'channel': r.get('channel'),
                    'message': re.sub(r'/tmp/axiom-material-program-[0-9]+/', '<worker>/', r['message']),
                    'locations': r.get('locations', []), 'causality': r.get('causality')}
                   for r in e.get('diagnostics', [])]
    return {'candidates': c, 'candidateActivation': d.get('nativeCandidateActivation'),
            'libraryCandidates': d.get('nativeLibraryCandidates'),
            'apiProviders': d.get('nativeApiProviders'),
            'gtfo': d['gtfoNativeCandidate'], 'queries': d['queries'],
            'gtfoConfiguredEnabled': d['gtfoConfiguredEnabled'], 'phase': e['phase'],
            'registeredMaterials': e['registeredMaterials'], 'nativeErrorCount': len(e['nativeErrors']),
            'diagnostics': diagnostics}


def compare(projected_path, reference_path, output):
    a = json.loads(projected_path.read_bytes()); b = json.loads(reference_path.read_bytes())
    if output.exists(): raise ValueError('comparison receipt must be new')
    if a['status'] != b['status'] or a['status'] != 'passed-bounded-observations':
        raise ValueError('both native candidate lanes must pass')
    if [r['name'] for r in a['runs']] != [r['name'] for r in b['runs']]: raise ValueError('native comparison cases differ')
    for x, y in zip(a['runs'], b['runs']):
        if x['response']['result']['execution']['addonDiscovery']['nativeCandidateDiscovery']['inputScope'] != 'entrypoints-and-metadata':
            raise ValueError('projection operand is not a projection')
        if y['response']['result']['execution']['addonDiscovery']['nativeCandidateDiscovery']['inputScope'] != 'complete-artifacts':
            raise ValueError('reference operand is not complete original artifacts')
        if comparable(x) != comparable(y): raise ValueError('native projected/full-artifact disagreement: '+x['name'])
    receipt = {'schema': 'axiom.native-candidate-projection-comparison.v1', 'status': 'passed',
               'cases': [r['name'] for r in a['runs']], 'activationQualified': False, 'wholePackParity': False,
               'completeAsmSubscriberTableEquivalent': False,
               'inputs': {str(p): sha256(p.read_bytes()).hexdigest() for p in (projected_path, reference_path)}}
    output.write_text(json.dumps(receipt, indent=2)+'\n')
    return receipt


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('java-home', 'engine-home', 'runtime-home', 'pack', 'report'):
        parser.add_argument('--'+name, type=Path, required=True)
    parser.add_argument('--reference-runtime-home', type=Path)
    parser.add_argument('--whole-pack', action='store_true'); args = parser.parse_args()
    saved = git(args.pack, 'show', selected_revisions()['supersymmetry']+':'+gtfo.CONFIG)
    def selected_cases(sussy): return corpus(sussy, saved)
    def run(runtime, report):
        return configuration.run(args.java_home, args.engine_home, runtime, args.pack, report, args.whole_pack,
                                 case_selector=selected_cases, result_checker=check_result,
                                 receipt_schema='axiom.native-candidate-metadata-observations.v1')
    run(args.runtime_home, args.report)
    if args.reference_runtime_home:
        reference = args.report.with_name(args.report.stem+'-full-reference.json')
        run(args.reference_runtime_home, reference)
        compare(args.report, reference, args.report.with_name(args.report.stem+'-comparison.json'))


if __name__ == '__main__': main()
