"""Supersymmetry authority for one material-backed-fluid runtime observation.

The Groovy probe is installed only in a disposable runtime projection.  It
reports registry state; it never creates or repairs the material under test.
"""

from __future__ import annotations

PROFILE_API_VERSION = 1

from dataclasses import dataclass
import base64
from hashlib import sha256
import json
from pathlib import Path
import re
from typing import Any, Mapping, NoReturn

from workbench_crucible_stage_snapshot import (
    build_stage_snapshot,
    registry_observation,
    validate_stage_snapshot,
)


MARKER_PREFIX = "[WORKBENCH-MATERIAL-FLUID-V1]"
PACK_PROFILE_ID = "workbench-pack:supersymmetry"
PLATFORM_PROFILE_ID = "workbench-platform:cleanroom:provisional"
MAX_LOG_BYTES = 16 * 1024 * 1024
_REGISTRY_NAME = re.compile(r"^[a-z][a-z0-9_]{0,127}$")
_SYMBOL = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]{0,127}$")
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_BASE64URL = re.compile(r"^[A-Za-z0-9_-]+$")
_ASSESSMENT_AUTHORITY = {
    "owner": "Atlas",
    "claim": "interpretation of one Crucible-observed Supersymmetry runtime marker",
    "construction_authority": "none",
}
_ASSESSMENT_LIMITATIONS = (
    "The observation applies only to the exact disposable projection and cold-start capture.",
    "It does not authorize a source edit, release, or mutation of an installed player instance.",
)


class MaterialFluidObservationError(ValueError):
    """The probe specification or retained observation is not trustworthy."""


def _fail(message: str) -> NoReturn:
    raise MaterialFluidObservationError(message)


def _canonical_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


@dataclass(frozen=True)
class MaterialFluidProbeSpec:
    registry_name: str
    symbol_name: str
    material_id: int
    color_rgb: int
    translation: str
    source_plan_id: str

    def __post_init__(self) -> None:
        if _REGISTRY_NAME.fullmatch(self.registry_name) is None:
            _fail("probe registry_name is not a safe Supersymmetry name")
        if _SYMBOL.fullmatch(self.symbol_name) is None:
            _fail("probe symbol_name is not a safe Groovy symbol")
        if type(self.material_id) is not int or not (0 <= self.material_id <= 32767):
            _fail("probe material_id is outside the supported registry range")
        if type(self.color_rgb) is not int or not (0 <= self.color_rgb <= 0xFFFFFF):
            _fail("probe color_rgb is not a 24-bit color")
        if not isinstance(self.translation, str) or not self.translation.strip():
            _fail("probe translation is missing")
        if len(self.translation.encode("utf-8")) > 1024:
            _fail("probe translation exceeds the byte limit")
        if not isinstance(self.source_plan_id, str) or not self.source_plan_id.startswith(
            "sha256:"
        ) or _SHA256.fullmatch(self.source_plan_id[7:]) is None:
            _fail("probe source_plan_id must be an exact SHA-256 identity")

    @property
    def material_resource(self) -> str:
        return f"susy:{self.registry_name}"

    def identity_material(self) -> dict[str, Any]:
        return {
            "color_rgb": self.color_rgb,
            "material_id": self.material_id,
            "material_resource": self.material_resource,
            "registry_name": self.registry_name,
            "source_plan_id": self.source_plan_id,
            "symbol_name": self.symbol_name,
            "translation": self.translation,
        }

    @property
    def probe_id(self) -> str:
        return "workbench-material-fluid-probe:sha256:" + sha256(
            _canonical_bytes(self.identity_material())
        ).hexdigest()


def _groovy_string(value: str) -> str:
    # JSON strings are valid Groovy string literals and avoid interpolation.
    return json.dumps(value, ensure_ascii=False)


def build_material_fluid_probe(spec: MaterialFluidProbeSpec) -> bytes:
    """Render the exact postInit observation script for a reviewed plan."""

    script = f'''// Generated by Workbench; disposable observation only.
import gregtech.api.GregTechAPI
import gregtech.api.fluids.store.FluidStorageKeys
import gregtech.api.unification.material.info.MaterialFlags
import gregtech.api.unification.material.properties.PropertyKey
import net.minecraftforge.fluids.FluidRegistry
import java.nio.charset.StandardCharsets
import java.util.Base64
import java.util.TreeMap

def expected = new TreeMap()
expected.put('color_rgb', {spec.color_rgb})
expected.put('fluid_name', {_groovy_string(spec.registry_name)})
expected.put('material_id', {spec.material_id})
expected.put('material_resource', {_groovy_string(spec.material_resource)})
expected.put('translation', {_groovy_string(spec.translation)})

def actual = new TreeMap()
def checks = new TreeMap()
def errorKind = null
try {{
    def manager = GregTechAPI.materialManager
    def material = manager == null ? null : manager.getMaterial(expected.material_resource)
    def fluid = material == null ? null : material.getFluid(FluidStorageKeys.LIQUID)

    actual.put('color_rgb', material == null ? null : material.getMaterialRGB())
    actual.put('fluid_name', fluid == null ? null : fluid.getName())
    actual.put('forge_registry_roundtrip', fluid != null && FluidRegistry.getFluid(fluid.getName())?.is(fluid))
    actual.put('has_flammable_flag', material != null && material.hasFlag(MaterialFlags.FLAMMABLE))
    actual.put('has_fluid_property', material != null && material.hasProperty(PropertyKey.FLUID))
    actual.put('localized_name', material == null ? null : material.getLocalizedName())
    actual.put('manager_phase', manager == null ? null : String.valueOf(manager.getPhase()))
    actual.put('material_id', material == null ? null : material.getId())
    actual.put('material_resource', material == null ? null : String.valueOf(material.getResourceLocation()))

    checks.put('color_rgb', actual.color_rgb == expected.color_rgb)
    checks.put('fluid_name', actual.fluid_name == expected.fluid_name)
    checks.put('forge_registry_roundtrip', actual.forge_registry_roundtrip == true)
    checks.put('has_flammable_flag', actual.has_flammable_flag == true)
    checks.put('has_fluid_property', actual.has_fluid_property == true)
    checks.put('localized_name', actual.localized_name == expected.translation)
    checks.put('manager_frozen', actual.manager_phase == 'FROZEN')
    checks.put('material_id', actual.material_id == expected.material_id)
    checks.put('material_resource', actual.material_resource == expected.material_resource)
}} catch (Throwable failure) {{
    errorKind = failure.getClass().getName()
}}

def success = errorKind == null && checks.size() == 9 && checks.values().every {{ it == true }}

// GroovyScript's sandbox does not expose groovy-json.  Keep this tiny encoder
// local, deterministic, and limited to the scalar/map shape of this marker.
def jsonQuote = {{ Object raw ->
    def out = new StringBuilder('"')
    String.valueOf(raw).each {{ character ->
        int code = (int) character
        if (code == 34) {{
            out.append((char) 92).append((char) 34)
        }} else if (code == 92) {{
            out.append((char) 92).append((char) 92)
        }} else if (code == 8) {{
            out.append((char) 92).append('b')
        }} else if (code == 12) {{
            out.append((char) 92).append('f')
        }} else if (code == 10) {{
            out.append((char) 92).append('n')
        }} else if (code == 13) {{
            out.append((char) 92).append('r')
        }} else if (code == 9) {{
            out.append((char) 92).append('t')
        }} else if (code < 32) {{
            out.append((char) 92).append('u').append(String.format('%04x', code))
        }} else {{
            out.append(character)
        }}
    }}
    out.append('"').toString()
}}
def jsonScalar = {{ Object value ->
    value == null ? 'null' :
            value instanceof Boolean ? (value ? 'true' : 'false') :
            value instanceof Number ? String.valueOf(value) : jsonQuote(value)
}}
def jsonMap = {{ Map value ->
    '{{' + new TreeMap(value).collect {{ key, item ->
        jsonQuote(key) + ':' + jsonScalar(item)
    }}.join(',') + '}}'
}}
def payloadJson = '{{' + [
        jsonQuote('actual') + ':' + jsonMap(actual),
        jsonQuote('checks') + ':' + jsonMap(checks),
        jsonQuote('error_kind') + ':' + jsonScalar(errorKind),
        jsonQuote('format') + ':' + jsonQuote('workbench-material-fluid-observation-v1'),
        jsonQuote('probe_id') + ':' + jsonQuote({_groovy_string(spec.probe_id)}),
        jsonQuote('source_plan_id') + ':' + jsonQuote({_groovy_string(spec.source_plan_id)}),
        jsonQuote('stage') + ':' + jsonQuote('postInit'),
        jsonQuote('state') + ':' + jsonQuote(success ? 'observed' : 'mismatch'),
].join(',') + '}}'
def encoded = Base64.getUrlEncoder().withoutPadding().encodeToString(
        payloadJson.getBytes(StandardCharsets.UTF_8))
log.infoMC({_groovy_string(MARKER_PREFIX)} + encoded)
if (!success) {{
    throw new IllegalStateException('Workbench material-backed-fluid assertion failed')
}}
'''
    encoded = script.encode("utf-8")
    if len(encoded) > 64 * 1024:
        _fail("generated material-backed-fluid probe exceeds the byte limit")
    return encoded


def build_material_fluid_probe_overlay(
    spec: MaterialFluidProbeSpec,
    *,
    source_name: str = "MaterialBackedFluidAssertion.groovy",
) -> dict[str, Any]:
    """Describe an exact create-only overlay for the disposable projection."""

    if source_name != "MaterialBackedFluidAssertion.groovy":
        _fail("material-backed-fluid probe V1 uses its fixed source name")
    script = build_material_fluid_probe(spec)
    material = {
        "probe_id": spec.probe_id,
        "source_plan_id": spec.source_plan_id,
        "source_sha256": sha256(script).hexdigest(),
        "target": ".minecraft/groovy/postInit/WorkbenchMaterialBackedFluidAssertion.groovy",
    }
    return {
        "format": "workbench-runtime-compatibility-file-overlay-v1",
        "schema_version": 1,
        "patch_id": "workbench-observation-probe:sha256:"
        + sha256(_canonical_bytes(material)).hexdigest(),
        "description": (
            "Disposable Supersymmetry postInit observation probe; it does not "
            "alter the source checkout or construct registry state."
        ),
        "target": {
            "path": material["target"],
            "must_be_absent": True,
        },
        "source": {
            "path": source_name,
            "sha256": material["source_sha256"],
        },
    }


def _decode_marker(log_bytes: bytes) -> dict[str, Any]:
    if not isinstance(log_bytes, bytes) or len(log_bytes) > MAX_LOG_BYTES:
        _fail("Groovy log is absent or exceeds the observation byte limit")
    try:
        text = log_bytes.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise MaterialFluidObservationError("Groovy log is not UTF-8") from exc
    tokens: list[str] = []
    for line in text.splitlines():
        index = line.find(MARKER_PREFIX)
        if index < 0:
            continue
        token = line[index + len(MARKER_PREFIX) :].strip()
        if _BASE64URL.fullmatch(token) is None:
            _fail("material-backed-fluid marker payload is malformed")
        tokens.append(token)
    if len(tokens) != 1:
        _fail("Groovy log must contain exactly one material-backed-fluid marker")
    token = tokens[0]
    try:
        raw = base64.urlsafe_b64decode(token + "=" * (-len(token) % 4))
        value = json.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise MaterialFluidObservationError(
            "material-backed-fluid marker is not canonical JSON data"
        ) from exc
    if not isinstance(value, dict) or _canonical_bytes(value) != raw:
        _fail("material-backed-fluid marker is not canonical JSON")
    return value


def _derived_checks(
    actual: Mapping[str, Any],
    spec: MaterialFluidProbeSpec,
) -> dict[str, bool]:
    return {
        "color_rgb": actual.get("color_rgb") == spec.color_rgb,
        "fluid_name": actual.get("fluid_name") == spec.registry_name,
        "forge_registry_roundtrip": actual.get("forge_registry_roundtrip") is True,
        "has_flammable_flag": actual.get("has_flammable_flag") is True,
        "has_fluid_property": actual.get("has_fluid_property") is True,
        "localized_name": actual.get("localized_name") == spec.translation,
        "manager_frozen": actual.get("manager_phase") == "FROZEN",
        "material_id": actual.get("material_id") == spec.material_id,
        "material_resource": actual.get("material_resource") == spec.material_resource,
    }


def _developer_assertions(checks: Mapping[str, bool]) -> dict[str, str]:
    assertion_groups = {
        "material_registration": {
            "color_rgb",
            "has_flammable_flag",
            "has_fluid_property",
            "manager_frozen",
            "material_id",
            "material_resource",
        },
        "fluid_registration": {
            "fluid_name",
            "forge_registry_roundtrip",
            "has_fluid_property",
            "manager_frozen",
        },
        "localization": {"localized_name"},
    }
    return {
        "groovy_compilation": "observed",
        **{
            key: (
                "observed"
                if all(checks.get(name) is True for name in required)
                else "failed"
            )
            for key, required in assertion_groups.items()
        },
    }


def _registry_semantic_descriptor(spec: MaterialFluidProbeSpec) -> dict[str, Any]:
    return {
        "domain": "material-backed-fluid",
        "kind": "material-fluid-registration",
        "key": {"material_resource": spec.material_resource},
    }


def _registry_provenance(
    spec: MaterialFluidProbeSpec,
    *,
    groovy_log_sha256: str,
) -> dict[str, Any]:
    return {
        "probe_id": spec.probe_id,
        "source_plan_id": spec.source_plan_id,
        "groovy_log_sha256": groovy_log_sha256,
    }


def interpret_material_fluid_observation(
    spec: MaterialFluidProbeSpec,
    *,
    groovy_log_bytes: bytes,
    capture: Mapping[str, Any],
) -> dict[str, Any]:
    """Validate one marker and project it into Crucible and Atlas authority."""

    capture_required = {
        "groovy_log_sha256",
        "groovy_log_uri",
        "launch_id",
        "launch_receipt_sha256",
        "launch_receipt_uri",
        "materialization_id",
        "materialization_receipt_sha256",
        "materialization_receipt_size",
        "materialization_receipt_uri",
        "payload",
        "probe_id",
        "probe_overlay_id",
        "probe_script_sha256",
        "session_outcome",
        "session_receipt_sha256",
        "session_receipt_size",
        "session_receipt_uri",
    }
    if set(capture) != capture_required:
        _fail("material-backed-fluid capture binding has unexpected fields")
    expected_script_sha256 = sha256(build_material_fluid_probe(spec)).hexdigest()
    expected_overlay_id = build_material_fluid_probe_overlay(spec)["patch_id"]
    if (
        not isinstance(capture["launch_id"], str)
        or not capture["launch_id"].startswith("sha256:")
        or _SHA256.fullmatch(capture["launch_id"][7:]) is None
        or _SHA256.fullmatch(str(capture["launch_receipt_sha256"])) is None
        or _SHA256.fullmatch(str(capture["groovy_log_sha256"])) is None
        or _SHA256.fullmatch(str(capture["session_receipt_sha256"])) is None
        or not isinstance(capture["materialization_id"], str)
        or not capture["materialization_id"].startswith("sha256:")
        or _SHA256.fullmatch(capture["materialization_id"][7:]) is None
        or _SHA256.fullmatch(
            str(capture["materialization_receipt_sha256"])
        ) is None
        or type(capture["materialization_receipt_size"]) is not int
        or not (0 < capture["materialization_receipt_size"] <= 4 * 1024 * 1024)
        or type(capture["session_receipt_size"]) is not int
        or not (0 < capture["session_receipt_size"] <= 4 * 1024 * 1024)
        or capture["groovy_log_sha256"] != sha256(groovy_log_bytes).hexdigest()
        or capture["probe_id"] != spec.probe_id
        or capture["probe_script_sha256"] != expected_script_sha256
        or capture["probe_overlay_id"] != expected_overlay_id
        or capture["session_outcome"] not in {"completed", "analysis-incomplete"}
        or not all(
            isinstance(capture[key], str) and capture[key].startswith("file:")
            for key in (
                "launch_receipt_uri",
                "materialization_receipt_uri",
                "groovy_log_uri",
                "session_receipt_uri",
            )
        )
        or not isinstance(capture["payload"], dict)
        or set(capture["payload"])
        != {"file_count", "total_bytes", "tree_sha256"}
        or not isinstance(capture["payload"]["tree_sha256"], str)
        or not capture["payload"]["tree_sha256"].startswith("sha256:")
        or _SHA256.fullmatch(capture["payload"]["tree_sha256"][7:]) is None
        or type(capture["payload"]["file_count"]) is not int
        or capture["payload"]["file_count"] < 1
        or type(capture["payload"]["total_bytes"]) is not int
        or capture["payload"]["total_bytes"] < 1
    ):
        _fail("material-backed-fluid capture does not bind the completed probe run")

    marker = _decode_marker(groovy_log_bytes)
    required = {
        "actual",
        "checks",
        "error_kind",
        "format",
        "probe_id",
        "source_plan_id",
        "stage",
        "state",
    }
    if set(marker) != required:
        _fail("material-backed-fluid marker has unexpected fields")
    if (
        marker["format"] != "workbench-material-fluid-observation-v1"
        or marker["probe_id"] != spec.probe_id
        or marker["source_plan_id"] != spec.source_plan_id
        or marker["stage"] != "postInit"
        or marker["state"] not in {"observed", "mismatch"}
        or not isinstance(marker["actual"], dict)
        or not isinstance(marker["checks"], dict)
        or marker["error_kind"] is not None
        and not isinstance(marker["error_kind"], str)
    ):
        _fail("material-backed-fluid marker does not bind the reviewed probe")
    expected_check_names = {
        "color_rgb",
        "fluid_name",
        "forge_registry_roundtrip",
        "has_flammable_flag",
        "has_fluid_property",
        "localized_name",
        "manager_frozen",
        "material_id",
        "material_resource",
    }
    if set(marker["checks"]) != expected_check_names or any(
        type(value) is not bool for value in marker["checks"].values()
    ):
        _fail("material-backed-fluid marker check set is malformed")
    actual_names = {
        "color_rgb",
        "fluid_name",
        "forge_registry_roundtrip",
        "has_flammable_flag",
        "has_fluid_property",
        "localized_name",
        "manager_phase",
        "material_id",
        "material_resource",
    }
    if set(marker["actual"]) != actual_names:
        _fail("material-backed-fluid marker actual state is malformed")
    derived_checks = _derived_checks(marker["actual"], spec)
    if marker["checks"] != derived_checks:
        _fail("material-backed-fluid marker checks contradict actual state")
    expected_observed = (
        marker["error_kind"] is None
        and all(marker["checks"].values())
    )
    if (marker["state"] == "observed") != expected_observed:
        _fail("material-backed-fluid marker state contradicts its checks")

    observation = registry_observation(
        stage="postInit",
        semantic_descriptor=_registry_semantic_descriptor(spec),
        registry_state={
            "actual": dict(marker["actual"]),
            "checks": dict(marker["checks"]),
            "state": marker["state"],
        },
        provenance=_registry_provenance(
            spec,
            groovy_log_sha256=sha256(groovy_log_bytes).hexdigest(),
        ),
    )
    snapshot = build_stage_snapshot(
        pack_profile_id=PACK_PROFILE_ID,
        platform_profile_id=PLATFORM_PROFILE_ID,
        stage="postInit",
        registry=[observation],
        effects=[],
        capture=dict(capture),
    )
    failed = sorted(
        name for name, passed in marker["checks"].items() if not passed
    )
    developer_assertions = _developer_assertions(marker["checks"])
    assessment_material = {
        "probe_id": spec.probe_id,
        "snapshot_id": snapshot["snapshot_id"],
        "source_plan_id": spec.source_plan_id,
        "state": marker["state"],
        "checks": dict(marker["checks"]),
        "developer_assertions": developer_assertions,
        "failed_checks": failed,
    }
    return {
        "format": "workbench-supersymmetry-material-fluid-assessment-v2",
        "schema_version": 2,
        "assessment_id": "workbench-atlas-material-fluid-assessment:sha256:"
        + sha256(_canonical_bytes(assessment_material)).hexdigest(),
        "authority": dict(_ASSESSMENT_AUTHORITY),
        "profile": {
            "pack_profile_id": PACK_PROFILE_ID,
            "platform_profile_id": PLATFORM_PROFILE_ID,
        },
        "probe": {
            **spec.identity_material(),
            "probe_id": spec.probe_id,
            "script_sha256": sha256(build_material_fluid_probe(spec)).hexdigest(),
        },
        "state": marker["state"],
        "checks": dict(marker["checks"]),
        "developer_assertions": developer_assertions,
        "failed_checks": failed,
        "observed": dict(marker["actual"]),
        "crucible_snapshot": snapshot,
        "limitations": list(_ASSESSMENT_LIMITATIONS),
    }


def validate_material_fluid_assessment(
    spec: MaterialFluidProbeSpec,
    assessment: Mapping[str, Any],
) -> dict[str, Any]:
    """Revalidate a retained Atlas assessment without upgrading its evidence."""

    required = {
        "assessment_id",
        "authority",
        "checks",
        "crucible_snapshot",
        "developer_assertions",
        "failed_checks",
        "format",
        "limitations",
        "observed",
        "probe",
        "profile",
        "schema_version",
        "state",
    }
    if not isinstance(assessment, Mapping) or set(assessment) != required:
        _fail("material-backed-fluid assessment has unexpected fields")
    profile = assessment.get("profile")
    probe = assessment.get("probe")
    checks = assessment.get("checks")
    observed = assessment.get("observed")
    snapshot = assessment.get("crucible_snapshot")
    expected_script_sha256 = sha256(build_material_fluid_probe(spec)).hexdigest()
    if (
        assessment.get("format")
        != "workbench-supersymmetry-material-fluid-assessment-v2"
        or assessment.get("schema_version") != 2
        or assessment.get("authority") != _ASSESSMENT_AUTHORITY
        or assessment.get("limitations") != list(_ASSESSMENT_LIMITATIONS)
        or profile
        != {
            "pack_profile_id": PACK_PROFILE_ID,
            "platform_profile_id": PLATFORM_PROFILE_ID,
        }
        or probe
        != {
            **spec.identity_material(),
            "probe_id": spec.probe_id,
            "script_sha256": expected_script_sha256,
        }
        or not isinstance(checks, Mapping)
        or not isinstance(observed, Mapping)
        or checks != _derived_checks(observed, spec)
        or any(type(value) is not bool for value in checks.values())
    ):
        _fail("material-backed-fluid assessment contradicts its bound probe")
    failed = sorted(name for name, passed in checks.items() if not passed)
    state = "observed" if not failed else "mismatch"
    developer_assertions = _developer_assertions(checks)
    if (
        assessment.get("state") != state
        or assessment.get("failed_checks") != failed
        or assessment.get("developer_assertions") != developer_assertions
    ):
        _fail("material-backed-fluid assessment state contradicts its checks")
    try:
        validated_snapshot = validate_stage_snapshot(snapshot)
    except (TypeError, ValueError) as exc:
        raise MaterialFluidObservationError(
            f"material-backed-fluid assessment has invalid Crucible custody: {exc}"
        ) from exc
    binding = validated_snapshot.get("binding")
    registry = validated_snapshot.get("registry")
    registry_record = (
        registry[0]
        if isinstance(registry, list)
        and len(registry) == 1
        and isinstance(registry[0], Mapping)
        else None
    )
    capture = binding.get("capture") if isinstance(binding, Mapping) else None
    groovy_log_sha256 = (
        capture.get("groovy_log_sha256") if isinstance(capture, Mapping) else None
    )
    if (
        not isinstance(binding, Mapping)
        or set(binding)
        != {"capture", "pack_profile_id", "platform_profile_id", "stage"}
        or binding.get("pack_profile_id") != PACK_PROFILE_ID
        or binding.get("platform_profile_id") != PLATFORM_PROFILE_ID
        or binding.get("stage") != "postInit"
        or not isinstance(capture, Mapping)
        or capture.get("probe_id") != spec.probe_id
        or capture.get("probe_script_sha256") != expected_script_sha256
        or capture.get("probe_overlay_id")
        != build_material_fluid_probe_overlay(spec)["patch_id"]
        or not isinstance(groovy_log_sha256, str)
        or _SHA256.fullmatch(groovy_log_sha256) is None
        or validated_snapshot.get("effects") != []
        or not isinstance(registry_record, Mapping)
        or registry_record.get("semantic_descriptor")
        != _registry_semantic_descriptor(spec)
        or registry_record.get("provenance")
        != {
            "authority": "Crucible",
            **_registry_provenance(
                spec,
                groovy_log_sha256=groovy_log_sha256 or "",
            ),
        }
        or registry_record.get("registry_state")
        != {"actual": dict(observed), "checks": dict(checks), "state": state}
    ):
        _fail("material-backed-fluid assessment and Crucible snapshot disagree")
    assessment_material = {
        "probe_id": spec.probe_id,
        "snapshot_id": validated_snapshot["snapshot_id"],
        "source_plan_id": spec.source_plan_id,
        "state": state,
        "checks": dict(checks),
        "developer_assertions": developer_assertions,
        "failed_checks": failed,
    }
    expected_id = "workbench-atlas-material-fluid-assessment:sha256:" + sha256(
        _canonical_bytes(assessment_material)
    ).hexdigest()
    if assessment.get("assessment_id") != expected_id:
        _fail("material-backed-fluid assessment identity is invalid")
    return dict(assessment)


def feature_studio_historical_recipe_reference() -> dict[str, Any]:
    """Return Atlas-owned legacy compatibility context for the first workspace."""

    return {
        "state": "historical-only",
        "profile_id": "legacy-forge-0.1.16.11",
        "snapshot_id": "SNAPSHOT-SUSY-0-1-16-11-9D3AA7AE0",
        "subjects": ["gregtech:oil_light", "susy:diluted_oil_light"],
        "limitation": (
            "This V1 evidence cannot establish current Cleanroom "
            "planned-versus-observed impact."
        ),
    }


__all__ = [
    "MARKER_PREFIX",
    "MaterialFluidObservationError",
    "MaterialFluidProbeSpec",
    "build_material_fluid_probe",
    "build_material_fluid_probe_overlay",
    "feature_studio_historical_recipe_reference",
    "interpret_material_fluid_observation",
    "validate_material_fluid_assessment",
]
